services:
  db:
    container_name: nutrilog-db
    image: ankane/pgvector
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

  api:
    container_name: nutrilog-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=${DOMAIN_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db

  ui:
    container_name: nutrilog-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "${UI_PORT}:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${DOMAIN_URL}
    depends_on:
      - api

  migrate:
    container_name: nutrilog-migrate
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db

volumes:
  db:
